name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build (Stable)
        run: cargo build --verbose
      - name: Test (Stable)
        run: cargo build --verbose
      - name: Package (Stable)
        run: cargo package
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build (Nightly)
        run: cargo build --verbose
      - name: Test (Nightly)
        run: cargo test --verbose
